### ISSUE TITLE
ImageJ - JSLIC Superpixels 2D - Java library errors on iMac

### ISSUE THREAD

**Issue by sakrig** [Borda/ij-CMP-BIA#6]
Recently, I started to get an error message when I run the JSLIC superpicels 2D plugin for ImageJ, and I think the error is *not* inside the JSLIC plugin, but rather is some sort of JAVA configuration error on my iMac. The error message is below, if anyone direct me towards a solution, or users group to discuss this error, I will be grateful.

ImageJ/plugins/segmentation/jSLIC segmentation 2D  *error*

(Fiji Is Just) ImageJ 2.0.0-rc-68/1.52i; Java 1.8.0_73 [64-bit]; Mac OS X 10.13.6; 461MB of 6032MB (7%)
 
java.lang.NoClassDefFoundError: net/miginfocom/layout/ComponentWrapper
	at org.scijava.ui.swing.console.ConsolePanel.initGui(ConsolePanel.java:110)
	at org.scijava.ui.swing.console.ConsolePanel.<init>(ConsolePanel.java:83)
	at org.scijava.ui.swing.console.SwingConsolePane.initLoggingPanel(SwingConsolePane.java:149)
	at org.scijava.ui.swing.console.SwingConsolePane.consolePanel(SwingConsolePane.java:143)
	at org.scijava.ui.swing.console.SwingConsolePane.append(SwingConsolePane.java:112)
	at org.scijava.ui.console.AbstractConsolePane.outputOccurred(AbstractConsolePane.java:60)
	at org.scijava.console.DefaultConsoleService.notifyListeners(DefaultConsoleService.java:131)
	at org.scijava.console.DefaultConsoleService$OutputStreamReporter.publish(DefaultConsoleService.java:227)
	at org.scijava.console.DefaultConsoleService$OutputStreamReporter.write(DefaultConsoleService.java:213)
	at org.scijava.console.MultiOutputStream.write(MultiOutputStream.java:90)
	at java.io.PrintStream.write(PrintStream.java:480)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	at sc.fiji.CMP_BIA.utils.Logging.logMsg(Logging.java:22)
	at sc.fiji.CMP_BIA.segmentation.superpixels.jSLIC.initInternalVaribales(jSLIC.java:110)
	at sc.fiji.CMP_BIA.segmentation.superpixels.jSLIC.<init>(jSLIC.java:95)
	at sc.fiji.CMP_BIA.segmentation.superpixels.jSLICp2D.<init>(jSLICp2D.java:38)
	at sc.fiji.CMP_BIA.plugins.jSLIC_superpixels_.processSelf(jSLIC_superpixels_.java:150)
	at sc.fiji.CMP_BIA.plugins.jSLIC_superpixels_.process(jSLIC_superpixels_.java:129)
	at sc.fiji.CMP_BIA.plugins.jSLIC_superpixels_.run(jSLIC_superpixels_.java:118)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.miginfocom.layout.ComponentWrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

**Comment by sakrig** [comment]
JSLIC plugin reproduces the problem, does not seem to be dependent on any particular image.

I have been using the JSLILC plugin for several years with no problems, I suspect there is some issue with updating Java, but my Java is at the latest version as of Dec. 5 2018.
